name: Fdroid Build Ermine


on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      app:
        type: string
        default: "com.deeperwire.ermine"
      version:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/ironfox-oss/ironfox:latest
    timeout-minutes: 420
    env:
      APP: ${{ inputs.app }}

    steps:
      - name: Checkout code
        run: |
          git clone https://gitlab.com/ironfox-oss/IronFox.git
          cd IronFox

      - name: Get sources
        run: |
          ls -la
          ./scripts/get_sources.sh

      - name: Prebuilt
        run: |
          ./scripts/prebuild.sh

      - name: Build
        run: |
          ./scripts/build.sh arm64
