name: Rebase

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
  schedule:
    - cron: "0 7 * * 6"

jobs:
  rebase_local_fennec_onto_upstream_fennec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: fennec

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add target repository as remote
        run: |
          git remote add upstream https://gitlab.com/relan/fennecbuild.git
          git fetch upstream master

      - name: Reset current branch onto target branch
        run: |
          git reset --hard upstream/master

      - name: Push updated branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force-with-lease

      # no more tags in fennec (when mull did have)
      # - name: Sync tags
      #   run: |
      #     git fetch upstream --tags
      #     git push --tags

  apply_ermine_onto_local_fennec:
    runs-on: ubuntu-latest
    needs: rebase_local_fennec_onto_upstream_fennec
    outputs:
      tag_created: ${{ steps.push_tags.outputs.tag_created }}
      TAG: ${{ steps.tag.outputs.TAG }}
      VERSION:: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: fennec

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get ermine scripts
        run: |
          git cherry-pick ..origin/ermine

      - name: Get build metadata
        run: |
          curl https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/org.mozilla.fennec_fdroid.yml --create-dirs -o ./-fdroiddata/metadata/com.deeperwire.ermine.yml

      - name: Set version from yaml if not provided
        id: version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            VERSION=$(yq '.Configs | last | .versionCode' ./-fdroiddata/metadata/com.deeperwire.ermine.yml)
            echo "Using version from YAML: $VERSION"
          else
            VERSION="${{ github.event.inputs.version }}"
            echo "Using provided version: $VERSION"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Generate missing tags
        run: |
          ./scripts/gen_tags.sh

      - name: Calculate latest tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Checkout latest tag
        env:
          TAG: ${{ steps.tag.outputs.TAG }}
        run: |
          git checkout $TAG

      - name: Get ermine scripts (again)
        run: |
          git cherry-pick ..origin/ermine

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape webp optipng

      - name: Apply ermine
        run: |
          ./scripts/ermine.sh $PWD
          git add -A
          git commit -m "Ermine"

      - name: Push tags
        id: push_tags
        env:
          TAG: ${{ steps.tag.outputs.TAG }}-ermine
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping push."
            echo "tag_created=false" >> "$GITHUB_OUTPUT"
          else
            echo "Creating and pushing tag $TAG."
            git tag -a "$TAG" -m ""
            git push --tags
            echo "tag_created=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Set latest
        if: ${{ steps.push_tags.outputs.tag_created == 'true' }}
        env:
          TAG: ${{ steps.tag.outputs.TAG }}-ermine
        run: |
          git checkout latest
          git reset --hard "$TAG"
          git push --force

  trigger_build:
    needs: apply_ermine_onto_local_fennec
    if: ${{ needs.apply_ermine_onto_local_fennec.outputs.tag_created == 'true' }}
    uses: ./.github/workflows/_build.yml
    with:
      ref: ${{ needs.apply_ermine_onto_local_fennec.outputs.TAG }}-ermine
      version: ${{ needs.apply_ermine_onto_local_fennec.outputs.VERSION }}
